// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgucprhdyxzklsawjcon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJndWNwcmhkeXh6a2xzYXdqY29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDE1MzEsImV4cCI6MjA3Mzg3NzUzMX0.bJtAYRO5eyPGIZqOEO_S3ucOFj4JobFeH6FvS3hlGjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});